### ISSUE TITLE
AddDynamicDataConfiguration explanation in documentation

### ISSUE THREAD

**Issue by JustinMinnaar** [riganti/dotvvm-dynamic-data#1]
Please update the documentation as it currently states...

To use Dynamic Data, add the following line to the DotvvmStartup.cs file.

    var dynamicDataConfig = config.AddDynamicDataConfiguration();

This needs to be added to the Configure method, and the dotvvmConfiguration option renamed as below.

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole();

            // use DotVVM
            var config = app.UseDotVVM<DotvvmStartup>(env.ContentRootPath);

            var dynamicDataConfig = config.AddDynamicDataConfiguration();

            // use static files
            app.UseStaticFiles(new StaticFileOptions
            {
                FileProvider = new Microsoft.Extensions.FileProviders.PhysicalFileProvider(env.WebRootPath)
            });
        }

**Comment by tomasherceg** [comment]
Thank you, I have updated the documentation to match the changes in DotVVM 1.1.
